title: Nexus Music Group UK
email: admin@nexusmusicgroup.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Specialising in the music industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nexusmusicgroup.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules